### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectE#12]
Hey :) 
As we are getting closer to deployment: Is there a recommendation which License we should specifiy in package.json?
I know there are things, which are more important, but the question just showed up in my mind..
@sacdallago

**Comment by gyachdav** [comment]
As a general rule of thumb use:
1.  for the website  - http://creativecommons.org/licenses/by/4.0/. In case third party content used (media, data) we should make attributions as needed. No copyrighted material should be used. 
2. for redistributable software use http://choosealicense.com/licenses/mit/ unless otherwise required by dependencies (shouldn't be the case)

**Comment by sacdallago** [comment]
Or alternatively just look at the LICENSE in every repo :D Also in yours:
https://github.com/Rostlab/JS16_ProjectE/blob/develop/LICENSE
