### ISSUE TITLE
Last reminder

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectE#3]
Dear @/all,

this is the last chance: I will turn on my computer while having my cereal tomorrow at 7 am CET, you better make sure I get:
- Which projects Emilyana, Ange and Javid whill be assigned to,
- What your plan is (goals, milestones, assignments) - also via github issues, I don't care. But it should be there

Jonas, Florian, Alex you are on the safer side, as I have seen already some progress from you, but don't get too relaxed. I still want them plan! :D
The other ones: brace yourselves... Christian is coming!

Remember: cereal happens at 7 a.m.!

**Comment by Emiliyana** [comment]
Dear Christian,

Emiliyana is currently on the trying to figure out, what the h*ck you
actually want from us in this project side. I checked the description of
the seminar again, and surprise surprise - it says that we don't need to
have any advanced knowledge of JavaScript or anything. Here is an exact
quotation of the description in tumonline:

Inhaltliche Voraussetzungen
(erwartete Kenntnisse)
keine
So my answer to your first question is - I'm currently trying to learn
JavaScript, Npm, Node.js, MongoDB, JQuery.

Now to your second question. Technically, unit tests are written by the
developers. And since our topic is "Build tools, continuous integration and
distribution" I'm not quite sure I understand how come we have to write the
unit tests, further on to write unit tests for not yet existing projects,
but okay. However, it seems we have a quite dynamic to-do list, since
Project A has also just been added to our responsibilities. So why that
being said, it's quite difficult to give you a "clear plan explaining what
are the goals, tasks and deadlines you set to get the project completed"
since there are

a) tasks which don't exactly belong to our topic
b) task regarding not yet existing stuff
c) additional responsibilities are being added

Moving on to your 3rd question - I'm trying to get at least a bit familiar
with the technologies used in the other project in order to pick a project
to be assigned to. Which is probably going to end with me being assigned to
the project left, so yeah, I'm doing useful stuff I guess :-D

4th question - sorry but communication so far has been a nightmare. I don't
know how many emails I have in my inbox, but here is what I don't have - an
overview over the whole thing. I believe you could have taken care of this
aspect since this is not the first time you hold this seminar and you are
more experienced in coordinating a big group.

And yey here comes the 5th question/point also know as the best chance to
turn into a black sheep in case I haven't already. Here are my thought and
concerns:
1. As I said, I find it very frustrating that there is no mentioning in the
   description that deep knowledge of JavaScript (and not only!) is expected.
2. This Seminar is 4 ECTS credits and from us is expected to code, present,
   AND write a 5 page long paper. I'm currently doing a block course in
   Spanish, which is 3 ECTS and I the workload that I have to do is probably
   1/50 of what is expected in your seminar.
3. The seminar is during the so called semester break, but I'm sure you are
   familiar that there is probably no TUM student that doesn't have retake
   exams .... ever.

So to put this all together - my biggest concern is that the relation
between the amount of effort, the given time and the ects "reward" for it
is out of balance and I'm afraid that it might affect my retakes. It seems
the seminar is not even remotely pursuant with the students. And by setting
additional "deadlines" and pressuring us is not exactly helpful and that
despite the fact that we wanted to meet you because we need help and don't
exactly know what to do.

Enjoy you cereal :-)

2016-03-03 19:21 GMT+01:00 Christian Dallago notifications@github.com:
